# Generated by Django 4.1.1 on 2022-10-02 11:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "verbose_name": "Producttt",
                "verbose_name_plural": "Productttsss",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
