# Generated by Django 4.1.1 on 2022-09-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[("c", "Completed"), ("p", "Pending"), ("I", "In-Progress")],
                max_length=2,
            ),
        ),
    ]
